FROM node:lts-slim

WORKDIR /home/node
RUN apt-get update && apt-get install -y git
RUN npm i -g @angular/cli
COPY package.json .
RUN npm i


# Angular Dev port
EXPOSE 4200

CMD ng serve --host 0.0.0.0 --disable-host-check --watch --poll 750
